### ISSUE TITLE
source code?

### ISSUE THREAD

**Issue by NeoFromMatrix** [OpenHisiIpCam/br-hisicam#1]
is there any code actually available?

**Comment by nikitos1550** [comment]
Hello! Later (month or two) here test binaries will be available. Source partly maybe same time, maybe later.

**Comment by pfalcon** [comment]
Any news?

**Comment by ZigFisher** [comment]
> Any news?
I had correspondence with the author, he is still busy.

Check out another our project - http://openipc.org
Perhaps in the future we will join forces with the author. 
He has very well done documentation. Respect to him.

**Comment by pfalcon** [comment]
@ZigFisher: Thanks for response and your work!
