### ISSUE TITLE
to support HI3516DV300+IMX385

### ISSUE THREAD

**Issue by LiyuCode** [OpenHisiIpCam/br-hisicam#10]
Thanks for the work.
Is there a plan to support HI3516DV300+IMX385 ?

**Comment by nikitos1550** [comment]
Hi! What do you mean?
As for base system there are several examples for hi3516cv300 family, and hi3516dv300 in particular.
There is no big issue to start up default system on your board.

As for videopipeline we have imx335 and imx327 boards, and some preliminary work already done to support them. Later (I think in several months) maybe we will be ready to add new CMOSes support. If you can help with example hardware please contact me directly (my email is on mine github profile page).
