### ISSUE TITLE
Which ipcam to get started?

### ISSUE THREAD

**Issue by multiple1** [OpenHisiIpCam/br-hisicam#13]
Hello!
Im interested in this project and want to try it out. 
I already own a Hi3516CV300 variant, but i don't think that this variant will have the best compatibility as i can see on the old kernel versions. 

Can you recommend me some ip cams to get started?

**Comment by nikitos1550** [comment]
Hi!
What is exact model of your camera?
hi3516cv300 is ok IMHO.

There are several configs for hi3516cv300 [here](https://github.com/OpenHisiIpCam/br-hisicam/tree/master/br-ext-hisicam/configs).

**Comment by multiple1** [comment]
https://de.aliexpress.com/item/32714159169.html
I bought the hi3516cv300 for h.265 but i think it is no big improvement with the cheap sensors.
Which cam would you recommend for a second one?

**Comment by nikitos1550** [comment]
If you want just to try any one is good. 
If you want some advice, explain your target, what do you want to do/develop?

**Comment by multiple1** [comment]
The usecase would be as a outdoor security cam, which has no fishy china software running.
Audio/Microphone would be nice.

**Comment by nikitos1550** [comment]
I think you can start with any cam you have. 3516cv300 is ok.
