### ISSUE TITLE
Job

### ISSUE THREAD

**Issue by denisrugo** [OpenHisiIpCam/br-hisicam#21]
Hello, I need to insert my logo on a camera based on HI3516CV300 IMX307 keeping the original firmware. Firmware 3516CV300_IMX307_B1T0A1M0C1P1_W_20.1.3.2
You do?
What the value ?
Thank you

**Comment by nikitos1550** [comment]
Hi, such inquiries can be done via info@openhisiipcam.org.
Github issues is wrong place.
Thanks for understanding.
