### ISSUE TITLE
wrong kernel version

### ISSUE THREAD

**Issue by ZigFisher** [OpenHisiIpCam/br-hisicam#9]
unknown_unknown_hi3516av100_unknown_defconfig
BR2_DEFAULT_KERNEL_VERSION="3.4.35"

ssqvision_on290h16d_hi3516dv100_imx290_defconfig
BR2_DEFAULT_KERNEL_VERSION="3.4.35"

unknown_unknown_hi3516dv100_unknown_defconfig
BR2_DEFAULT_KERNEL_VERSION="3.4.35"

or

xm_ipg-83h50p-b_hi3516av100_imx178_defconfig
BR2_DEFAULT_KERNEL_VERSION="4.9.37"

xm_83h40pl-b_hi3516dv100_ov4689_defconfig
BR2_DEFAULT_KERNEL_VERSION="4.9.37"

**Comment by nikitos1550** [comment]
thanks, fixed
